### PR TITLE
handle new docker-desktop name

### LINKED ISSUE #39: Error installing on Docker Desktop
There appear to be 2 problems with installing onto k8s in Docker Desktop

1. The node name for recent Docker Desktop builds should be `docker-desktop` (see #37)
2. `localhost:6444` endpoint for talking to k8s API from inside the invocation-image container does not appear to work.

```
$ duffle install myriff riff --credentials myk8s
Executing install action...
time="2019-05-31T17:15:53Z" level=fatal msg="Get https://localhost:6443/api/v1/nodes/minikube: dial tcp 127.0.0.1:6443: connect: connection refused"
Error: Install step failed: container exit code: 1
```

### PR DESCRIPTION
**Pull request by sbawaska**
replaces #37 by fixing unit test failures.
Also, replace the master server URL for docker desktop from localhost to host.docker.internal
so that it can be discovered from within the container executing CNAB install

closes #39.

### CODE REVIEW

**Comment by sbawaska** [comment]
I tried to come up with instructions first, but there is no good way to simplify the steps. The problem is outlined here: https://github.com/projectriff/cnab-k8s-installer-base/issues/39#issuecomment-498382850
To make the cnab install work on docker-desktop, users will have to 
1. change `~/.kube/config` to replace `localhost` with `host.docker.internal`
1. run duffle install 
1. change back `host.docker.internal` to `localhost` in `~/.kube/config` otherwise kubectl will not work ( since `host.docker.internal` is not resolvable from the host itself).

Then repeat the same steps for uninstall.

Also, if the user has `watch kubectl get pods --all-namespaces` running during install (as we have documented previously) that will now break, since `~/.kube/config` is pointing at `host.docker.internal` which is not resolvable from host.

If the user misses any of the steps outlined, they are going to have problems installing OR running kubectl after install. I feel that the above prescriptive flow for our users is more brittle than us trying to patch kubeconfig.

**Comment by scothis** [comment]
> To make the cnab install work on docker-desktop, users will have to <snip>

Yea, we don't want users to manually edit the kube config.

We can do better by either:
- allowing the user to specify the k8s api server host as a config input, using the kube config value as a default
- encourage one-off kubeconfig files
- other [mechanisms to authenticate](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) to the api server

We can figure out what the right balance of config options.

**Comment by scothis** [comment]
Another option, run the invocation image inside the k8s cluster. This way we don’t need a local docker daemon.

**Comment by glyn** [comment]
> How does the CNAB community manage k8s configurations? I have to imagine the Docker folks have solved this.

I'm investigating this.

**Comment by glyn** [comment]
docker-app patches the kube config for docker desktop when creating a CNAB from a _docker application package_. However, they hit the same problem as duffle when using an CNAB which has not undergone this patching.

**Comment by sbawaska** [comment]
We now run the invocationImage in cluster, hence this is not longer applicable.

**Pull request closed without merging**
